@file:Suppress("INTERFACE_WITH_SUPERCLASS", "OVERRIDING_FINAL_MEMBER", "RETURN_TYPE_MISMATCH_ON_OVERRIDE", "CONFLICTING_OVERLOADS")

package io.framed.exporter.ecore

open external class EcorePackageLiterals {
    companion object {
        var EMODELELEMENT: Number
        var EMODELELEMENT_FEATURE_COUNT: Number
        var EMODELELEMENT_OPERATION_COUNT: Number
        var EMODELELEMENT_EANNOTATIONS: Number
        var ENAMEDELEMENT: Number
        var ENAMEDELEMENT_FEATURE_COUNT: Number
        var ENAMEDELEMENT_OPERATION_COUNT: Number
        var ENAMEDELEMENT_EANNOTATIONS: Number
        var ENAMEDELEMENT_NAME: Number
        var ETYPEDELEMENT: Number
        var ETYPEDELEMENT_FEATURE_COUNT: Number
        var ETYPEDELEMENT_OPERATION_COUNT: Number
        var ETYPEDELEMENT_EANNOTATIONS: Number
        var ETYPEDELEMENT_NAME: Number
        var ETYPEDELEMENT_ORDERED: Number
        var ETYPEDELEMENT_UNIQUE: Number
        var ETYPEDELEMENT_LOWERBOUND: Number
        var ETYPEDELEMENT_UPPERBOUND: Number
        var ETYPEDELEMENT_MANY: Number
        var ETYPEDELEMENT_REQUIRED: Number
        var ETYPEDELEMENT_ETYPE: Number
        var ETYPEDELEMENT_EGENERICTYPE: Number
        var ESTRUCTURALFEATURE: Number
        var ESTRUCTURALFEATURE_FEATURE_COUNT: Number
        var ESTRUCTURALFEATURE_OPERATION_COUNT: Number
        var ESTRUCTURALFEATURE_EANNOTATIONS: Number
        var ESTRUCTURALFEATURE_NAME: Number
        var ESTRUCTURALFEATURE_ORDERED: Number
        var ESTRUCTURALFEATURE_UNIQUE: Number
        var ESTRUCTURALFEATURE_LOWERBOUND: Number
        var ESTRUCTURALFEATURE_UPPERBOUND: Number
        var ESTRUCTURALFEATURE_MANY: Number
        var ESTRUCTURALFEATURE_REQUIRED: Number
        var ESTRUCTURALFEATURE_ETYPE: Number
        var ESTRUCTURALFEATURE_EGENERICTYPE: Number
        var ESTRUCTURALFEATURE_CHANGEABLE: Number
        var ESTRUCTURALFEATURE_VOLATILE: Number
        var ESTRUCTURALFEATURE_TRANSIENT: Number
        var ESTRUCTURALFEATURE_DEFAULTVALUELITERAL: Number
        var ESTRUCTURALFEATURE_DEFAULTVALUE: Number
        var ESTRUCTURALFEATURE_UNSETTABLE: Number
        var ESTRUCTURALFEATURE_DERIVED: Number
        var ESTRUCTURALFEATURE_ECONTAININGCLASS: Number
        var EATTRIBUTE: Number
        var EATTRIBUTE_FEATURE_COUNT: Number
        var EATTRIBUTE_OPERATION_COUNT: Number
        var EATTRIBUTE_EANNOTATIONS: Number
        var EATTRIBUTE_NAME: Number
        var EATTRIBUTE_ORDERED: Number
        var EATTRIBUTE_UNIQUE: Number
        var EATTRIBUTE_LOWERBOUND: Number
        var EATTRIBUTE_UPPERBOUND: Number
        var EATTRIBUTE_MANY: Number
        var EATTRIBUTE_REQUIRED: Number
        var EATTRIBUTE_ETYPE: Number
        var EATTRIBUTE_EGENERICTYPE: Number
        var EATTRIBUTE_CHANGEABLE: Number
        var EATTRIBUTE_VOLATILE: Number
        var EATTRIBUTE_TRANSIENT: Number
        var EATTRIBUTE_DEFAULTVALUELITERAL: Number
        var EATTRIBUTE_DEFAULTVALUE: Number
        var EATTRIBUTE_UNSETTABLE: Number
        var EATTRIBUTE_DERIVED: Number
        var EATTRIBUTE_ECONTAININGCLASS: Number
        var EATTRIBUTE_ID: Number
        var EATTRIBUTE_EATTRIBUTETYPE: Number
        var EANNOTATION: Number
        var EANNOTATION_FEATURE_COUNT: Number
        var EANNOTATION_OPERATION_COUNT: Number
        var EANNOTATION_EANNOTATIONS: Number
        var EANNOTATION_SOURCE: Number
        var EANNOTATION_DETAILS: Number
        var EANNOTATION_EMODELELEMENT: Number
        var EANNOTATION_CONTENTS: Number
        var EANNOTATION_REFERENCES: Number
        var ECLASSIFIER: Number
        var ECLASSIFIER_FEATURE_COUNT: Number
        var ECLASSIFIER_OPERATION_COUNT: Number
        var ECLASSIFIER_EANNOTATIONS: Number
        var ECLASSIFIER_NAME: Number
        var ECLASSIFIER_INSTANCECLASSNAME: Number
        var ECLASSIFIER_INSTANCECLASS: Number
        var ECLASSIFIER_DEFAULTVALUE: Number
        var ECLASSIFIER_INSTANCETYPENAME: Number
        var ECLASSIFIER_EPACKAGE: Number
        var ECLASSIFIER_ETYPEPARAMETERS: Number
        var ECLASS: Number
        var ECLASS_FEATURE_COUNT: Number
        var ECLASS_OPERATION_COUNT: Number
        var ECLASS_EANNOTATIONS: Number
        var ECLASS_NAME: Number
        var ECLASS_INSTANCECLASSNAME: Number
        var ECLASS_INSTANCECLASS: Number
        var ECLASS_DEFAULTVALUE: Number
        var ECLASS_INSTANCETYPENAME: Number
        var ECLASS_EPACKAGE: Number
        var ECLASS_ETYPEPARAMETERS: Number
        var ECLASS_ABSTRACT: Number
        var ECLASS_INTERFACE: Number
        var ECLASS_ESUPERTYPES: Number
        var ECLASS_EOPERATIONS: Number
        var ECLASS_EALLATTRIBUTES: Number
        var ECLASS_EALLREFERENCES: Number
        var ECLASS_EREFERENCES: Number
        var ECLASS_EATTRIBUTES: Number
        var ECLASS_EALLCONTAINMENTS: Number
        var ECLASS_EALLOPERATIONS: Number
        var ECLASS_EALLSTRUCTURALFEATURES: Number
        var ECLASS_EALLSUPERTYPES: Number
        var ECLASS_EIDATTRIBUTE: Number
        var ECLASS_ESTRUCTURALFEATURES: Number
        var ECLASS_EGENERICSUPERTYPES: Number
        var ECLASS_EALLGENERICSUPERTYPES: Number
        var EDATATYPE: Number
        var EDATATYPE_FEATURE_COUNT: Number
        var EDATATYPE_OPERATION_COUNT: Number
        var EDATATYPE_EANNOTATIONS: Number
        var EDATATYPE_NAME: Number
        var EDATATYPE_INSTANCECLASSNAME: Number
        var EDATATYPE_INSTANCECLASS: Number
        var EDATATYPE_DEFAULTVALUE: Number
        var EDATATYPE_INSTANCETYPENAME: Number
        var EDATATYPE_EPACKAGE: Number
        var EDATATYPE_ETYPEPARAMETERS: Number
        var EDATATYPE_SERIALIZABLE: Number
        var EENUM: Number
        var EENUM_FEATURE_COUNT: Number
        var EENUM_OPERATION_COUNT: Number
        var EENUM_EANNOTATIONS: Number
        var EENUM_NAME: Number
        var EENUM_INSTANCECLASSNAME: Number
        var EENUM_INSTANCECLASS: Number
        var EENUM_DEFAULTVALUE: Number
        var EENUM_INSTANCETYPENAME: Number
        var EENUM_EPACKAGE: Number
        var EENUM_ETYPEPARAMETERS: Number
        var EENUM_SERIALIZABLE: Number
        var EENUM_ELITERALS: Number
        var EENUMLITERAL: Number
        var EENUMLITERAL_FEATURE_COUNT: Number
        var EENUMLITERAL_OPERATION_COUNT: Number
        var EENUMLITERAL_EANNOTATIONS: Number
        var EENUMLITERAL_NAME: Number
        var EENUMLITERAL_VALUE: Number
        var EENUMLITERAL_INSTANCE: Number
        var EENUMLITERAL_LITERAL: Number
        var EENUMLITERAL_EENUM: Number
        var EFACTORY: Number
        var EFACTORY_FEATURE_COUNT: Number
        var EFACTORY_OPERATION_COUNT: Number
        var EFACTORY_EANNOTATIONS: Number
        var EFACTORY_EPACKAGE: Number
        var EOBJECT: Number
        var EOBJECT_FEATURE_COUNT: Number
        var EOBJECT_OPERATION_COUNT: Number
        var EOPERATION: Number
        var EOPERATION_FEATURE_COUNT: Number
        var EOPERATION_OPERATION_COUNT: Number
        var EOPERATION_EANNOTATIONS: Number
        var EOPERATION_NAME: Number
        var EOPERATION_ORDERED: Number
        var EOPERATION_UNIQUE: Number
        var EOPERATION_LOWERBOUND: Number
        var EOPERATION_UPPERBOUND: Number
        var EOPERATION_MANY: Number
        var EOPERATION_REQUIRED: Number
        var EOPERATION_ETYPE: Number
        var EOPERATION_EGENERICTYPE: Number
        var EOPERATION_ECONTAININGCLASS: Number
        var EOPERATION_ETYPEPARAMETERS: Number
        var EOPERATION_EPARAMETERS: Number
        var EOPERATION_EEXCEPTIONS: Number
        var EOPERATION_EGENERICEXCEPTIONS: Number
        var EPACKAGE: Number
        var EPACKAGE_FEATURE_COUNT: Number
        var EPACKAGE_OPERATION_COUNT: Number
        var EPACKAGE_EANNOTATIONS: Number
        var EPACKAGE_NAME: Number
        var EPACKAGE_NSURI: Number
        var EPACKAGE_NSPREFIX: Number
        var EPACKAGE_EFACTORYINSTANCE: Number
        var EPACKAGE_ECLASSIFIERS: Number
        var EPACKAGE_ESUBPACKAGES: Number
        var EPACKAGE_ESUPERPACKAGE: Number
        var EPARAMETER: Number
        var EPARAMETER_FEATURE_COUNT: Number
        var EPARAMETER_OPERATION_COUNT: Number
        var EPARAMETER_EANNOTATIONS: Number
        var EPARAMETER_NAME: Number
        var EPARAMETER_ORDERED: Number
        var EPARAMETER_UNIQUE: Number
        var EPARAMETER_LOWERBOUND: Number
        var EPARAMETER_UPPERBOUND: Number
        var EPARAMETER_MANY: Number
        var EPARAMETER_REQUIRED: Number
        var EPARAMETER_ETYPE: Number
        var EPARAMETER_EGENERICTYPE: Number
        var EPARAMETER_EOPERATION: Number
        var EREFERENCE: Number
        var EREFERENCE_FEATURE_COUNT: Number
        var EREFERENCE_OPERATION_COUNT: Number
        var EREFERENCE_EANNOTATIONS: Number
        var EREFERENCE_NAME: Number
        var EREFERENCE_ORDERED: Number
        var EREFERENCE_UNIQUE: Number
        var EREFERENCE_LOWERBOUND: Number
        var EREFERENCE_UPPERBOUND: Number
        var EREFERENCE_MANY: Number
        var EREFERENCE_REQUIRED: Number
        var EREFERENCE_ETYPE: Number
        var EREFERENCE_EGENERICTYPE: Number
        var EREFERENCE_CHANGEABLE: Number
        var EREFERENCE_VOLATILE: Number
        var EREFERENCE_TRANSIENT: Number
        var EREFERENCE_DEFAULTVALUELITERAL: Number
        var EREFERENCE_DEFAULTVALUE: Number
        var EREFERENCE_UNSETTABLE: Number
        var EREFERENCE_DERIVED: Number
        var EREFERENCE_ECONTAININGCLASS: Number
        var EREFERENCE_CONTAINMENT: Number
        var EREFERENCE_CONTAINER: Number
        var EREFERENCE_RESOLVEPROXIES: Number
        var EREFERENCE_EOPPOSITE: Number
        var EREFERENCE_EREFERENCETYPE: Number
        var EREFERENCE_EKEYS: Number
        var ESTRINGTOSTRINGMAPENTRY: Number
        var ESTRINGTOSTRINGMAPENTRY_FEATURE_COUNT: Number
        var ESTRINGTOSTRINGMAPENTRY_OPERATION_COUNT: Number
        var ESTRINGTOSTRINGMAPENTRY_KEY: Number
        var ESTRINGTOSTRINGMAPENTRY_VALUE: Number
        var EGENERICTYPE: Number
        var EGENERICTYPE_FEATURE_COUNT: Number
        var EGENERICTYPE_OPERATION_COUNT: Number
        var EGENERICTYPE_EUPPERBOUND: Number
        var EGENERICTYPE_ETYPEARGUMENTS: Number
        var EGENERICTYPE_ERAWTYPE: Number
        var EGENERICTYPE_ELOWERBOUND: Number
        var EGENERICTYPE_ETYPEPARAMETER: Number
        var EGENERICTYPE_ECLASSIFIER: Number
        var ETYPEPARAMETER: Number
        var ETYPEPARAMETER_FEATURE_COUNT: Number
        var ETYPEPARAMETER_OPERATION_COUNT: Number
        var ETYPEPARAMETER_EANNOTATIONS: Number
        var ETYPEPARAMETER_NAME: Number
        var ETYPEPARAMETER_EBOUNDS: Number
        var EBIGDECIMAL: Number
        var EBIGINTEGER: Number
        var EBOOLEAN: Number
        var EBOOLEANOBJECT: Number
        var EBYTE: Number
        var EBYTEARRAY: Number
        var EBYTEOBJECT: Number
        var ECHAR: Number
        var ECHARACTEROBJECT: Number
        var EDATE: Number
        var EDIAGNOSTICCHAIN: Number
        var EDOUBLE: Number
        var EDOUBLEOBJECT: Number
        var EELIST: Number
        var EENUMERATOR: Number
        var EFEATUREMAP: Number
        var EFEATUREMAPENTRY: Number
        var EFLOAT: Number
        var EFLOATOBJECT: Number
        var EINT: Number
        var EINTEGEROBJECT: Number
        var EJAVACLASS: Number
        var EJAVAOBJECT: Number
        var ELONG: Number
        var ELONGOBJECT: Number
        var EMAP: Number
        var ERESOURCE: Number
        var ERESOURCESET: Number
        var ESHORT: Number
        var ESHORTOBJECT: Number
        var ESTRING: Number
        var ETREEITERATOR: Number
        var EINVOCATIONTARGETEXCEPTION: Number
    }
}